version: '3'
services:
  gdbdebug:
    build: # use the Dockerfile in the current directory
      context: ./.docker/gdb/
      dockerfile: Dockerfile
    security_opt: # options needed for gdb debugging
      - seccomp:unconfined
      - apparmor:unconfined
    container_name: gdbdebug
    ports:
      - "7776:22" # SSH
      - "7777:7777" # GDB Server
    restart: always
    #volumes:
    #  - ./:/home/gdbdebug
